(() => {
  const ago = milliseconds => new Date(Date.now() - milliseconds).toISOString();

  window.SFS_MOCK_LEADS = [
    {
      leadId: 'SFS-1048',
      source: 'Website form',
      customerName: 'Maya Chen',
      email: 'maya@greenmountaincoffeeclub.com',
      phone: '+1 (802) 555-0148',
      company: 'Green Mountain Coffee Club',
      originalInquiry: 'Hi! We need 300 custom coffee scoop clips with our logo for subscriber boxes going out October 10. We have an SVG and one sample idea, but I am not sure what material would hold up best. Can you quote it and tell me if the date is realistic?',
      aiSummary: '300 branded coffee scoop clips needed by Oct 10. Logo file is ready; customer needs material guidance and a production quote.',
      urgency: 'High',
      missingInformation: ['Target budget', 'Final scoop dimensions'],
      recommendedNextAction: 'Confirm the deadline is workable, request dimensions, and offer a paid sample before the full run.',
      preparedResponse: 'Hi Maya — thanks for reaching out. A run of 300 by October 10 looks realistic, and I can help choose a material that will stand up to regular use. Could you send the scoop dimensions and your target budget? Once I have those, I can confirm pricing and prepare a sample before the full run.',
      status: 'Needs response',
      assignedPerson: 'Jonathan',
      createdTimestamp: ago(47 * 1000),
      updatedTimestamp: ago(47 * 1000),
      firstResponseTimestamp: null
    },
    {
      leadId: 'SFS-1047',
      source: 'Direct email',
      customerName: 'Evan Morales',
      email: 'evan@vermontcomfort.co',
      phone: '+1 (802) 555-0182',
      company: 'Vermont Comfort Co.',
      originalInquiry: 'We miss calls while the team is in basements and crawl spaces. I want something that collects the customer issue from our website, tells us which requests are urgent, and gives my office manager a reply she can approve. We get around 25 to 40 inquiries a week. What would a small pilot look like?',
      aiSummary: 'Local HVAC company wants a pilot for website intake, urgency triage, and staff-approved replies. Volume: 25–40 inquiries/week.',
      urgency: 'High',
      missingInformation: ['Current website platform', 'Who should receive alerts'],
      recommendedNextAction: 'Offer a 20-minute discovery call and ask about the current website and office workflow.',
      preparedResponse: 'Hi Evan — this is exactly the kind of workflow we are designing for. A focused pilot could capture website inquiries, flag urgent requests, and prepare a response for your office manager to approve. What platform is your website on, and who currently watches incoming requests? If helpful, I can also set up a 20-minute call to map the smallest useful pilot.',
      status: 'Needs response',
      assignedPerson: 'Jonathan',
      createdTimestamp: ago(8 * 60 * 1000),
      updatedTimestamp: ago(8 * 60 * 1000),
      firstResponseTimestamp: null
    },
    {
      leadId: 'SFS-1046',
      source: 'Referral',
      customerName: 'Alina Roy',
      email: 'alina@lakehouseinnvt.com',
      phone: '+1 (802) 555-0109',
      company: 'Lake House Inn',
      originalInquiry: 'Ben at North Country Events sent me. We are reopening our east wing next month and need about 500 premium room-key tags plus a small set of lobby wayfinding signs. Our board meets Monday morning and I need a rough range before then. Is this something you can handle?',
      aiSummary: 'High-value referral: 500 premium room-key tags plus lobby signage. Rough price range needed before Monday board meeting.',
      urgency: 'Urgent',
      missingInformation: ['Sign count and sizes', 'Desired materials', 'Installation needed or not'],
      recommendedNextAction: 'Acknowledge immediately, confirm a budgetary range can be delivered tomorrow, and request the sign schedule.',
      preparedResponse: 'Hi Alina — thanks to you and Ben for thinking of us. We can explore both the 500 room-key tags and the lobby wayfinding set, and I can get you a useful budgetary range before your Monday meeting. Could you send the approximate number and sizes of the signs, preferred materials if known, and whether you need installation? I’ll review it and follow up with next steps tomorrow.',
      status: 'New',
      assignedPerson: '',
      createdTimestamp: ago(2 * 60 * 1000),
      updatedTimestamp: ago(2 * 60 * 1000),
      firstResponseTimestamp: null
    },
    {
      leadId: 'SFS-1045',
      source: 'Website form',
      customerName: 'Priya Nair',
      email: 'priya@littlepines.org',
      phone: null,
      company: 'Little Pines Preschool',
      originalInquiry: 'We are refreshing our preschool brand and would like a friendlier logo, a roadside banner, and a simple parent handout. Attached are the colors we use now. Our director prefers to keep the tree idea but make it feel less corporate.',
      aiSummary: 'Preschool needs a logo refresh, roadside banner, and parent handout. Keep the existing tree concept but make it warmer.',
      urgency: 'Normal',
      missingInformation: ['Decision deadline', 'Banner dimensions'],
      recommendedNextAction: 'Wait for the requested dimensions and decision date before scoping the design package.',
      preparedResponse: 'Hi Priya — thank you for the helpful direction. Keeping the tree while making the identity feel warmer gives us a strong starting point. When you have a chance, could you send the banner dimensions and the date you hope to select a direction? I can then outline the right-sized design package.',
      status: 'Waiting on customer',
      assignedPerson: 'Cindy',
      createdTimestamp: ago(34 * 60 * 1000),
      updatedTimestamp: ago(16 * 60 * 1000),
      firstResponseTimestamp: ago(18 * 60 * 1000)
    },
    {
      leadId: 'SFS-1044',
      source: 'Direct email',
      customerName: 'Derek Bell',
      email: 'dbell72@example.com',
      phone: null,
      company: null,
      originalInquiry: 'Need something printed. How much? Call me.',
      aiSummary: 'Vague 3D-print request with no object, quantity, dimensions, file, deadline, or phone number.',
      urgency: 'Normal',
      missingInformation: ['What needs printing', 'Quantity', 'Dimensions or model file', 'Deadline', 'Phone number'],
      recommendedNextAction: 'Send a short qualifying reply asking for the object, quantity, size, deadline, and an STL/STEP file or photos.',
      preparedResponse: 'Hi Derek — happy to take a look. What would you like printed, how many do you need, and roughly how large is it? If you have an STL or STEP file, please attach it; otherwise, a few photos and dimensions will help. Also send the best phone number and your deadline, and I can point you toward a price.',
      status: 'Needs response',
      assignedPerson: 'Jonathan',
      createdTimestamp: ago(3 * 60 * 60 * 1000),
      updatedTimestamp: ago(3 * 60 * 60 * 1000),
      firstResponseTimestamp: null
    },
    {
      leadId: 'SFS-1043',
      source: 'Manual entry',
      customerName: 'Marcus Webb',
      email: 'marcus@webbfab.example',
      phone: '+1 (802) 555-0196',
      company: 'Webb Fabrication',
      originalInquiry: 'Can you reproduce a broken load-bearing steel gear from our milling machine? It has to handle high torque and I need the finished metal part by Tuesday.',
      aiSummary: 'Industrial customer needs a load-bearing steel gear reproduced by Tuesday. Outside SFS fabrication capability and safety profile.',
      urgency: 'Low',
      missingInformation: [],
      recommendedNextAction: 'Close as poor fit and refer the customer to a qualified machine shop; do not imply SFS can fabricate or certify the part.',
      preparedResponse: 'Hi Marcus — thanks for checking with us. We are not equipped to reproduce or certify a load-bearing steel machine component, so we would not be the right shop for this job. A qualified CNC machine shop or industrial gear specialist should be able to assess the part safely. I do not want to hold up your search, so I’m closing this request on our side.',
      status: 'Closed',
      assignedPerson: 'Jonathan',
      createdTimestamp: ago(26 * 60 * 60 * 1000),
      updatedTimestamp: ago(25 * 60 * 60 * 1000),
      firstResponseTimestamp: ago((25 * 60 + 12) * 60 * 1000)
    }
  ];
})();
